FaceControlApp.Web/Models/ErrorViewModel.cs
namespace FaceControlApp.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
    }
}

FaceControlApp.Web/Controllers/AppController.cs
namespace FaceControlApp.Web.Controllers
{
    using MediatR;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.DependencyInjection;

    public class AppController : Controller
    {
        private IMediator _mediator;

        protected IMediator Mediator => this._mediator ??= this.HttpContext.RequestServices.GetService<IMediator>();
    }
}

FaceControlApp.Web/Controllers/BiometricalIdentifiersController.cs
namespace FaceControlApp.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using FaceControlApp.Domain.Entities;
    using FaceControlApp.Persistence;
    using FaceControlApp.Application.Aggregates.BiometricalIdentifiers.Commands.CreateBoimetricalIdentifier;
    using FaceControlApp.Application.Aggregates.BiometricalIdentifiers.Queries.GetBiometricalIdentifier;

    public class BiometricalIdentifiersController : AppController
    {
        private FaceControlAppDbContext Context
        {
            get;
        }

        public BiometricalIdentifiersController(FaceControlAppDbContext context)
        {
            this.Context = context;
        }

        // GET: BiometricalIdentifiers
        public async Task<IActionResult> Index()
        {
            return this.View(await this.Context.BiometricalIdentifiers.ToListAsync());
        }

        // GET: BiometricalIdentifiers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            try
            {
                var result = await this.Mediator.Send(new GetBiometricalIdentifierQuery
                {
                    Id = id.Value
                });

                return this.View(result);
            }
            catch
            {
                return this.NotFound();
            }
        }

        // GET: BiometricalIdentifiers/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: BiometricalIdentifiers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBiometricalIdentifierCommand command)
        {
            var result = await this.Mediator.Send(command);

            return this.RedirectToAction("Details", new { id = result});
        }

        // GET: BiometricalIdentifiers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var biometricalIdentifier = await this.Context.BiometricalIdentifiers.FindAsync(id);
            if (biometricalIdentifier == null)
            {
                return this.NotFound();
            }
            return this.View(biometricalIdentifier);
        }

        // POST: BiometricalIdentifiers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,PersonName,FaceImage")] BiometricalIdentifier biometricalIdentifier)
        {
            if (id != biometricalIdentifier.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.Context.Update(biometricalIdentifier);
                    await this.Context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.BiometricalIdentifierExists(biometricalIdentifier.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return this.RedirectToAction(nameof(Index));
            }
            return this.View(biometricalIdentifier);
        }

        // GET: BiometricalIdentifiers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var biometricalIdentifier = await this.Context.BiometricalIdentifiers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (biometricalIdentifier == null)
            {
                return this.NotFound();
            }

            return this.View(biometricalIdentifier);
        }

        // POST: BiometricalIdentifiers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var biometricalIdentifier = await this.Context.BiometricalIdentifiers.FindAsync(id);
            this.Context.BiometricalIdentifiers.Remove(biometricalIdentifier);
            await this.Context.SaveChangesAsync();
            return this.RedirectToAction(nameof(Index));
        }

        private bool BiometricalIdentifierExists(Guid id)
        {
            return this.Context.BiometricalIdentifiers.Any(e => e.Id == id);
        }
    }
}

FaceControlApp.Web/Controllers/HomeController.cs
namespace FaceControlApp.Web.Controllers
{
    using FaceControlApp.Web.Models;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using System.Diagnostics;

    public class HomeController : AppController
    {
        private ILogger<HomeController> Logger
        {
            get;
        }

        public HomeController(ILogger<HomeController> logger)
        {
            this.Logger = logger;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

FaceControlApp.Web/Controllers/SuspectsController.cs
namespace FaceControlApp.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using FaceControlApp.Application.Aggregates.Suspects.Commands.VerifySuspect;
    using FaceControlApp.Application.Aggregates.Suspects.Queries.GetSuspectDetails;
    using FaceControlApp.Application.Aggregates.Suspects.Queries.GetSuspects;
    using Microsoft.AspNetCore.Mvc;

    public class SuspectsController : AppController
    {
        public async Task<IActionResult> Index()
        {
            var result = await this.Mediator.Send(new GetSuspectsQuery());

            return this.View(result);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            try
            {
                var result = await this.Mediator.Send(new GetSuspectDetailsQuery
                {
                    Id = id.Value
                });

                return this.View(result);
            }
            catch
            {
                return this.NotFound();
            }
        }

        public async Task<IActionResult> Verify(Guid? id)
        {
            try
            {
                var result = await this.Mediator.Send(new GetSuspectDetailsQuery
                {
                    Id = id.Value
                });

                return this.View(result);
            }
            catch
            {
                return this.NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Verify(VerifySuspectCommand command)
        {
            var result = await this.Mediator.Send(command);

            return this.RedirectToAction("Details", "BiometricaIdentifiers", new { id = result });
        }
    }
}

FaceControlApp.Web/Views/BiometricalIdentifiers/Create.cshtml
@model FaceControlApp.Application.Aggregates.BiometricalIdentifiers.Commands.CreateBoimetricalIdentifier.CreateBiometricalIdentifierCommand

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BiometricalIdentifier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonName" class="control-label"></label>
                <input asp-for="PersonName" class="form-control" />
                <span asp-validation-for="PersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaceImage" class="control-label"></label>
                <input asp-for="FaceImage" type="file" class="form-control-file" />
                <span asp-validation-for="FaceImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FaceControlApp.Web/Views/BiometricalIdentifiers/Delete.cshtml
@model FaceControlApp.Domain.Entities.BiometricalIdentifier

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BiometricalIdentifier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FaceImage)
        </dt>
        <dd class="col-sm-10">
            <img src="data:image/jpg;base64,@Model.FaceImage" width="600">
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FaceControlApp.Web/Views/BiometricalIdentifiers/Details.cshtml
@model FaceControlApp.Application.Aggregates.BiometricalIdentifiers.Models.BiometricalIdentifierViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BiometricalIdentifier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FaceImageBase64)
        </dt>
        <dd class = "col-sm-10">
            <img src="data:image/jpg;base64,@Model.FaceImageBase64" width="600">
        </dd>
    </dl>
    
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FaceControlApp.Web/Views/BiometricalIdentifiers/Edit.cshtml
@model FaceControlApp.Domain.Entities.BiometricalIdentifier

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BiometricalIdentifier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PersonName" class="control-label"></label>
                <input asp-for="PersonName" class="form-control" />
                <span asp-validation-for="PersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaceImage" class="control-label"></label>
                <input asp-for="FaceImage" class="form-control" />
                <span asp-validation-for="FaceImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FaceControlApp.Web/Views/BiometricalIdentifiers/Index.cshtml
@model IEnumerable<FaceControlApp.Domain.Entities.BiometricalIdentifier>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PersonName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaceImage)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.PersonName)</a>
            </td>
            <td>
                <img src="data:image/jpg;base64,@item.FaceImage" width="250">
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FaceControlApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    #videoElement {
        width: 640px;
        height: 480px;
        background-color: #666;
    }
</style>

<div class="text-center">
    <h1 class="display-4">Real-time camera stream</h1>
    <div id="container">
        <video autoplay id="videoElement">
        </video>
    </div>
</div>

<script>
    var video = document.querySelector("#videoElement");

    if (navigator.mediaDevices.getUserMedia) {
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(function (stream) {
                video.srcObject = stream;
            })
            .catch(function (err0r) {
                console.log("Something went wrong!");
            });
    }
</script>

FaceControlApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FaceControlApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Real-time stream</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BiometricalIdentifiers" asp-action="Index">Biometrical Identifiers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suspects" asp-action="Index">Suspects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FaceControlApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FaceControlApp.Web/Views/Suspects/Details.cshtml
@model FaceControlApp.Domain.Entities.Suspect

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Suspect</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FaceImage)
        </dt>
        <dd class = "col-sm-10">
            <img src="data:image/jpg;base64,@Model.FaceImage" width="600">
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Verify" asp-route-id="@Model.Id" class="btn btn-success">Verify</a>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

FaceControlApp.Web/Views/Suspects/Index.cshtml
@model IEnumerable<FaceControlApp.Domain.Entities.Suspect>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FaceImage)
            </th>
            <th>@Html.DisplayNameFor(model => model.ShootingDate)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">
                    <img src="data:image/jpg;base64,@item.FaceImage" width="250">
                </a>
            </td>
            <td>
                <p>@item.ShootingDate</p>
            </td>
            <td>
                <a asp-action="Verify" asp-route-id="@item.Id" class="btn btn-success">Verify</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FaceControlApp.Web/Views/Suspects/Verify.cshtml
@model FaceControlApp.Domain.Entities.Suspect

@{
    ViewData["Title"] = "Verify";
}
<style>
    .suspect-face-image {
        margin-bottom: 16px;
    }
</style>

<h1>Verify</h1>

<h4>Suspect</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Verify">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <img src="data:image/jpg;base64,@Model.FaceImage" width="600" class="suspect-face-image">
                <input class="form-control" placeholder="Enter person name here" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}